default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
development:
  <<: *default
  database: nengoWeb_development
test:
  <<: *default
  database: nengoWeb_test
production:
  <<: *default
  database: nengoWeb_production
  username: nengoio
  password: <%= ENV['NENGOWEB_DATABASE_PASSWORD'] %>
