default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: nengoWeb_development
test:
  <<: *default
  database: nengoWeb_test
production:
  <<: *default
  database: nengoWeb_production
  username: nengoWeb
  password: <%= ENV['NENGOWEB_DATABASE_PASSWORD'] %>
